services:
  postgres:
    container_name: postgresql-bsn
    image: postgres
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      PGDATA: /var/data/postgresql/data
      POSTGRES_DB: book-social-network
    volumes:
      - postgres:/data/postgres
    ports:
      - 5432:5432
    networks:
      - spring-demo
    restart: unless-stopped
  mail-dev:
    container_name: mail-dev-bsn
    image: maildev/maildev
    ports:
      - 1080:1080
      - 1025:1025

volumes:
  postgres:
    driver: local
networks:
  spring-demo:
    driver: bridge